[General]
bypass-system = true
ipv6 = true

[Proxy]
# HTTP: <title> = http,<host>,<port>,<user>,<password>[,tfo=true][,flag=<flag>]
# Shadowsocks: <title> = ss,<host>,<port>,password=<password>,method=<method>[,tfo=true][,flag=<flag>]
ds720-plus = ss,gordonhui.synology.me,8388,password=PASSWORD,method=2022-blake3-aes-128-gcm,tfo=true
ecs-sg = ss,gordonhui.synology.me,8389,password=PASSWORD,method=2022-blake3-aes-128-gcm,tfo=true,flag=SG
gluetun = http,gordonhui.synology.me,8888,gordon,PASSWORD

[Rule]
# Company internal services via Gluetun
IP-CIDR,8.220.218.11/32,GLUETUN // 佳悅 A100
IP-CIDR,8.220.223.209/32,GLUETUN // 算法 A100
IP-CIDR,47.236.125.171/32,GLUETUN // 24/7 ECS
DOMAIN,ai-material.ichamet.net,GLUETUN
DOMAIN,yearning.rchamet.com,GLUETUN
DOMAIN,wiki.ichamet.com,GLUETUN
DOMAIN,devgit.01bite.net,GLUETUN

# Apple Intelligence, ChatGPT
DOMAIN,gspe1-ssl.ls.apple.com,ECS-SG
DOMAIN,apple-relay.apple.com,ECS-SG
DOMAIN-KEYWORD,openai,ECS-SG
DOMAIN-KEYWORD,chatgpt,ECS-SG

# Home network
IP-CIDR,192.168.0.0/16,DS720-PLUS

# Final
FINAL,DIRECT
