[General]
bypass-system = true
ipv6 = true
update-url = https://raw.githubusercontent.com/gordonhwc/shadowrocket-configs/refs/heads/main/touhou.conf

[Proxy Group]
🇹🇼🇯🇵 = url-test,东方网络,use=true,interval=60,policy-regex-filter=^(🇹🇼|🇯🇵)[^（]*$

[Rule]
# Company internal services via Gluetun
IP-CIDR,8.220.218.11/32,GLUETUN // 佳悅 A100
IP-CIDR,8.220.223.209/32,GLUETUN // 算法 A100
IP-CIDR,47.236.125.171/32,GLUETUN // 24/7 ECS
DOMAIN,yearning.rchamet.com,GLUETUN
DOMAIN,wiki.ichamet.com,GLUETUN
DOMAIN,devgit.01bite.net,GLUETUN

# Apple Intelligence, ChatGPT
DOMAIN,gspe1-ssl.ls.apple.com,🇹🇼🇯🇵
DOMAIN,apple-relay.apple.com,🇹🇼🇯🇵
DOMAIN-KEYWORD,openai,🇹🇼🇯🇵
DOMAIN-KEYWORD,chatgpt,🇹🇼🇯🇵

# Home network
IP-CIDR,192.168.0.0/16,DS720-PLUS

# Final
FINAL,DIRECT
